HOTEL_MANAGEMENT:
  EQUIPMENTS:
    LIGHT:
      TYPE: LIGHT
      POWER_CONSUMPTION: 5
      DEFAULT_STATE: "OFF"
    AIRCONDITIONER: 
      TYPE: AIRCONDITIONER
      POWER_CONSUMPTION: 10
      DEFAULT_STATE: "ON"
  EQUIPMENTSTATE:
    ON_STATE: "ON"
    OFF_STATE: "OFF"
  CORRIDORTYPE:
    MAINCORRIDOR: MAINCORRIDOR
    SUBCORRIDOR: SUBCORRIDOR
  SENSORINPUT: 
    MOVEMENT: MOVEMENT
    NO_MOVEMENT: NO_MOVEMENT
  TIMESLOT:
    DAY: DAY
    NIGHT: NIGHT